
  CREATE TABLE "USERS" 
   (	"U_NO" NUMBER(4,0) NOT NULL ENABLE, 
	"U_ID" VARCHAR2(50 BYTE), 
	"UNAME" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"POST_TIME" DATE, 
	"NATION" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	 PRIMARY KEY ("U_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "C##HIMZOO"."USERS"."U_NO" IS '회원번호AUTO';
   COMMENT ON COLUMN "C##HIMZOO"."USERS"."U_ID" IS '아이디';
   COMMENT ON COLUMN "C##HIMZOO"."USERS"."UNAME" IS '이름';
   COMMENT ON COLUMN "C##HIMZOO"."USERS"."GENDER" IS '성별';
   COMMENT ON COLUMN "C##HIMZOO"."USERS"."POST_TIME" IS '등록일';
   COMMENT ON COLUMN "C##HIMZOO"."USERS"."NATION" IS '국가CODE';
   COMMENT ON COLUMN "C##HIMZOO"."USERS"."CITY" IS '나라CODE';
   COMMENT ON TABLE "C##HIMZOO"."USERS"  IS '회원정보';